service: eaddb

image: lyrasis/eaddb

builder:
  arch: amd64

registry:
  server: "localhost:5555"

ssh:
  config: true
  user: ubuntu

volumes:
  - "/storage/eaddb:/rails/storage"

env:
  clear:
    RAILS_ASSUME_SSL: true
    RAILS_ENV: production
    RAILS_FORCE_SSL: true
    RAILS_LOG_TO_STDOUT: true
    SCOUT_AUTO_INSTRUMENTS: true
    SCOUT_LOG_FILE_PATH: STDOUT
    SCOUT_MONITOR: true
  secret:
    - ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
    - ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
    - ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - SCOUT_KEY
    - SECRET_KEY_BASE
